export const NOTES_LOADING = 'NOTES_LOADING'
export const ADD_NOTE = 'ADD_NOTE'
export const DELETE_NOTE = 'DELETE_NOTE'
export const UPDATE_NOTE = 'UPDATE_NOTE'
export const GET_NOTES = 'GET_NOTES'

export const TASKERS_LOADING = 'TASKERS_LOADING'
export const GET_TASKERS = 'GET_TASKERS'
export const ADD_TASKER = 'ADD_TASKER'
export const UPDATE_TASKER = 'UPDATE_TASKER'
export const DELETE_TASKER = 'DELETE_TASKER'

export const ADD_TASK = 'ADD_TASK'
export const UPDATE_TASK = 'UPDATE_TASK'
export const DELETE_TASK = 'DELETE_TASK'

export const NOTEBOOK_LOADING = 'NOTEBOOK_LOADING'
export const GET_NOTEBOOK = 'GET_NOTEBOOK'
export const CREATE_NOTEBOOK = 'CREATE_NOTEBOOK'
export const DELETE_NOTEBOOK = 'DELETE_NOTEBOOK'
export const UPDATE_NOTEBOOK = 'UPDATE_NOTEBOOK'

export const CREATE_ERROR = 'CREATE_ERROR'
export const HAS_ERROR = 'HAS_ERROR'