name: Deploy backend


on:
  push:
    branches: [ master ]

jobs:
  
  build:
    env:
      workdir: ./shnotes_backend
      jardir: ./shnotes_backend/build/libs/*
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    - name: Build with Gradle
      working-directory: ${{env.workdir}}
      run: gradle bootJar
      
    - name: Copy jar to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        source: "${{env.jardir}}"
        target: "${{ secrets.REMOTE_BACKEND_DIR }}"
      
    - name: Restart Linux service
      uses: appleboy/ssh-action@master
      with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: /etc/init.d/sharednotes restart
    
      
