name: Deploy database


on:
  push:
    paths: 
      - 'database/**'
    branches: [ master ]

jobs:
  
  build:
    env:
      workdir: ./database
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Copy to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        source: "${{env.workdir}}"
        target: "${{ secrets.REMOTE_BACKEND_DIR }}"

    - name: Database migration
      uses: appleboy/ssh-action@master
      with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
        
          script: |
            cd ${{env.workdir}}
            gradle -i flywayMigrate
      
